<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
declare(strict_types=1);

namespace Magefan\AutoRelatedProductPlus\Block\Widget;

use Magefan\AutoRelatedProduct\Block\RelatedProductList;
use Magefan\AutoRelatedProduct\Model\Config\Source\RelatedTemplate;
use Magento\Widget\Block\BlockInterface;

class RelatedList extends RelatedProductList implements BlockInterface
{
    public function toHtml(): string
    {
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
}
