<?php
/**
 * Copyright © 2016 Ubertheme.com All rights reserved.
 */
?>
<!-- Initial ajax add cart js function -->
<script type="text/javascript">
    require([
        "jquery",
        "Ubertheme_Base/js/ajaxAddCart",
        "domReady!"
    ], function ($) {
        'use strict';

        ubAjaxCartOptions = <?= $block->getAjaxCartOptions() ?>;
        ubAjaxCartOptions.messageTimeout = MESSAGE_TIMEOUT ? MESSAGE_TIMEOUT : 5000;
        $.ub.AjaxAddCart(ubAjaxCartOptions);
    });
</script>



