<?php
/**
 * Copyright © 2016 Ubertheme.com All rights reserved.
 */
?>
<!-- Initial ajax compare js function -->
<script type="text/javascript">
    require([
        "jquery",
        "Ubertheme_Base/js/ajaxCompare",
        "domReady!"
    ], function ($) {
        'use strict';

        const options = <?= $block->getAjaxCompareOptions() ?>;
        options.messageTimeout = MESSAGE_TIMEOUT ? MESSAGE_TIMEOUT : 5000;
        $.ub.AjaxCompare(options);
    });
</script>


