<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Cookie\Block\Html\Notices $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
/** @var \Magento\Cookie\Helper\Cookie $cookieHelper */
$cookieHelper = $block->getData('cookieHelper');
if ($cookieHelper->isCookieRestrictionModeEnabled()): ?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block">
        <div role="document" class="content" tabindex="0">
            <div class="message-content">
                <h3><?= $block->escapeHtml(__('Ovaj web adresa koristi kolačiće')) ?></h3>
                <p><?= $block->escapeHtml(__(
                    'Koristimo kolačiće za personalizaciju sadržaja i oglasa, omogućavanje značajki društvenih mreža i analizu našeg prometa. Također dijelimo informacije o vašem korištenju naše stranice s našim partnerima za društvene mreže, oglašavanje i analitiku, koji ih mogu kombinirati s drugim podacima koje ste im dali ili koje su prikupili putem vašeg korištenja njihovih usluga.'
                )) ?>
                </p>
                <!--<?= $block->escapeHtml(__('<a href="%1">Vidi više</a>.', $block->getPrivacyPolicyLink()), ['a']) ?>-->
                </div>
            <div class="actions">

                <button id="btn-cookie-view-more" class="action view-more primary" style="background: #fff; color: #000">
                    <?= $block->escapeHtml(__('<a href="%1">Vidi više</a>.', $block->getPrivacyPolicyLink()), ['a']) ?>
                </button>

                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('Dozvoli kolačiće')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div#notice-cookie-block') ?>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $cookieHelper->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $cookieHelper->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->getUrl('cookie/index/noCookies')) ?>"
                }
            }
        }
    </script>
<?php endif; ?>



<style>


/* Initially position the block below the viewport */
.message.global.cookie {
    opacity: 0;
    transform: translateY(100px); /* Move down by 100px */
    animation: slideIn 0.3s ease-in-out 3s forwards; /* Delay of 2 seconds */
}

/* Keyframes to animate the block into view */
@keyframes slideIn {
    to {
        opacity: 1;
        transform: translateY(0); /* Normal position */
    }
}

#notice-cookie-block{
    position: fixed;
    width: 100%;
    height: 100%;
    background: #00000040;
    background: transparent;
    top: 0px;
    bottom: 0px;
    left: 0px;
    right: 0px;
    padding: 0px;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 99;
    @media (max-width:768px)  {
        align-items: flex-end;
    }
}
#notice-cookie-block h3{
    margin-bottom: 24px;
}
#notice-cookie-block .content{
    max-width: 900px;
    background: #fff;
    padding: 24px;
    border-radius: 8px;
    margin: 12px;
    box-shadow: 1px 1px 10px #00000033;
}
#notice-cookie-block .actions{
    display: flex;
    flex-direction: row;
    justify-content: flex-end;
    flex-wrap: wrap;
    margin-top: 24px;
}
#notice-cookie-block .actions .action {
    margin-left: 12px;
    padding: 12px 24px;
    border-radius: 4px;
    @media (max-width:768px)  {
        width: 100%;
        margin: 0px;
        margin-bottom: 12px;
    }
}
#notice-cookie-block .actions .action span{
    font-weight: normal;
}
#notice-cookie-block .message-content p{
    margin-top: 12px;
    margin-bottom: 12px;
}
</style>