<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$_product = $block->getProduct();
$customAttributeValue = $_product->getData('garancija');
?>
<div class="custom-attribute">
    <?php if ($customAttributeValue): ?>
        <p><?php echo $block->escapeHtml($customAttributeValue); ?></p>
    <?php else: ?>
        <p><?php echo __('Ova infomracija trenutno nije dostupna!'); ?></p>
    <?php endif; ?>
</div>