<?php
/** @var \Magento\Catalog\Block\Product\View $block */
$_product = $block->getProduct();
$customAttributeValue = $_product->getData('warranty');
?>
<div class="custom-attribute">
    <?php if ($customAttributeValue): ?>
        <?php 
        if($customAttributeValue == 438){
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('garancija_ostalo')
                ->toHtml();
        } 

        if($customAttributeValue == 437){
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('garancija_nakit')
                ->toHtml();
        } 

        if($customAttributeValue == 436){
            echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('garancija_satovi')
                ->toHtml();
        } 
        ?>
    <?php else: ?>
        <p><?php echo __('Ova infomracija trenutno nije dostupna!'); ?></p>
    <?php endif; ?>
</div>